# Travis continuous integration for Kitodo.Production

dist: xenial

language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - ant-optional
      - tomcat7-common

cache:

env:

script: ant -lib /usr/share/tomcat7/lib all
